# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataSearcher
                                 A QGIS plugin
 Search data by preset queries in json
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-11
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Zlatanov Evgeniy
        email                : johnzet@yandex.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant, QSize
from qgis.PyQt.QtGui import QIcon, QIntValidator, QDoubleValidator
from qgis.PyQt.QtWidgets import QAction, QTableWidgetItem, QApplication, QDialog
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.core import QgsProject, QgsVectorLayer, QgsRelation, QgsDataSourceUri, QgsWkbTypes 
from qgsdatetimeedit import QgsDateTimeEdit
from qgsfilterlineedit import QgsFilterLineEdit
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .about import AbtDialog, AbtInfo
from .data_searcher_dockwidget import DataSearcherDockWidget
import os.path
import json
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import datetime

class DataSearcher:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
    
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DataSearcher_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Data Searcher')

        self.toolbar = self.iface.addToolBar(u'Экстрапоиск')
        self.toolbar.setObjectName(u'DataSearcher')

        #print "** INITIALIZING DataSearcher"

        self.pluginIsActive = False
        self.dockwidget = None
        self.fieldsLayout = None

        self.settings = None
        self.layer = None
        self.connInfo = None
        self.column_key = None

        self.ui_about = None

    # about button
    def show_about(self):
        self.ui_about.setWindowFlags(self.ui_about.windowFlags() | Qt.WindowStaysOnTopHint | Qt.WindowMinMaxButtonsHint)
        self.ui_about.show()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DataSearcher', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)
            # self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/_Data_searcher/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Экстрапоиск'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING DataSearcher"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False

        self.disconnectActions()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD DataSearcher"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Data Searcher'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""
        # print("run start: ", datetime.now().strftime("%H:%M:%S.%f")[:-3])
        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING DataSearcher"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = DataSearcherDockWidget()
                # self.fieldsLayout = self.dockwidget.fieldsLayout
                self.fieldsLayout = self.dockwidget.fieldsGroupBox.layout().itemAt(0)

                self.loadLayersData()
                
                # about button
                self.ui_about = AbtDialog()
                info = AbtInfo()
                self.dockwidget.pushButton_about.setToolTip(
                    "О программе:\nМодуль: {0}\nВерсия: {1}\nРазработчик: {2}"
                        .format(info.pluginName, info.version, info.creator)
                )

            self.populateComboLayers()
            self.setRowSelectedButtonsStatus()

            self.connectActions()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

        # print("run end: ", datetime.now().strftime("%H:%M:%S.%f")[:-3])

    def connectActions(self):
        # QgsProject.instance().cleared.connect(self.closePanel)
        self.dockwidget.buttonSearch.clicked.connect(self.execSearch)
        self.dockwidget.buttonRefreshLayers.clicked.connect(self.populateComboLayers)
        self.dockwidget.buttonReset.clicked.connect(self.execReset)
        self.dockwidget.buttonCenter.clicked.connect(self.centerToSelect)
        self.dockwidget.buttonZoom.clicked.connect(self.zoomToSelect)
        self.dockwidget.buttonCopy.clicked.connect(self.copySelected)
        self.dockwidget.buttonFilterMap.clicked.connect(self.filterMapBySelect)
        self.dockwidget.buttonClearFilterMap.clicked.connect(self.clearFilterMapBySelect)
        self.dockwidget.tableResult.itemDoubleClicked.connect(self.execDoubleClickedTable)
        self.dockwidget.tableResult.itemSelectionChanged.connect(self.setRowSelectedButtonsStatus)
        self.dockwidget.pushButton_about.clicked.connect(self.show_about)
        if self.dockwidget:
            self.dockwidget.combo_layers.currentIndexChanged.connect(self.comboLayersChanged)
        # print("connect")

    def disconnectActions(self):
        # QgsProject.instance().cleared.disconnect(self.closePanel)
        self.dockwidget.buttonSearch.clicked.disconnect(self.execSearch)
        self.dockwidget.buttonRefreshLayers.clicked.disconnect(self.populateComboLayers)
        self.dockwidget.buttonReset.clicked.disconnect(self.execReset)
        self.dockwidget.buttonCenter.clicked.disconnect(self.centerToSelect)
        self.dockwidget.buttonZoom.clicked.disconnect(self.zoomToSelect)
        self.dockwidget.buttonCopy.clicked.disconnect(self.copySelected)
        self.dockwidget.buttonFilterMap.clicked.disconnect(self.filterMapBySelect)
        self.dockwidget.buttonClearFilterMap.clicked.disconnect(self.clearFilterMapBySelect)
        self.dockwidget.combo_layers.currentIndexChanged.disconnect(self.comboLayersChanged)
        self.dockwidget.tableResult.itemDoubleClicked.disconnect(self.execDoubleClickedTable)
        self.dockwidget.tableResult.itemSelectionChanged.disconnect(self.setRowSelectedButtonsStatus)
        self.dockwidget.pushButton_about.clicked.disconnect(self.show_about)
        # print('disconnect')

    def loadLayersData(self):
        with open(os.path.join(self.plugin_dir, "settings.json"), "r") as read_file:
            self.settings = json.load(read_file)
            for layer in self.settings["Layers"].keys():
                self.dockwidget.combo_layers.addItem(layer)

    def comboLayersChanged(self):
        # print("comboLayersChanged..")
        if self.dockwidget.combo_layers.count() <= 0:
            self.clearForms()
            return
        if self.dockwidget.combo_layers.currentIndex() < 0:
            self.clearForms()
            return

        #self.layer = self.dockwidget.combo_layers.currentLayer()
        self.layer = self.dockwidget.combo_layers.currentData()
        if self.layer:
            self.connInfo = QgsDataSourceUri(self.layer.dataProvider().dataSourceUri(expandAuthConfig=True))
        self.populateFilterFields()

    def clearForms(self):
        self.layer = None
        self.clearFieldsLayout(self.fieldsLayout)
        self.dockwidget.tableResult.setRowCount(0)
        self.dockwidget.tableResult.sortItems(-1)

    def populateComboLayers(self):
        self.dockwidget.combo_layers.clear()

        available_layers = self.settings["Layers"].keys()

        for layer in QgsProject.instance().mapLayers().values():
            if layer.name() in available_layers:
                self.dockwidget.combo_layers.addItem(layer.name(), layer)

        if self.dockwidget.combo_layers.count() < 1:
            self.clearForms()
            return

        curlayer = self.iface.activeLayer()
        if curlayer is not None:
            if curlayer.name() in available_layers:
                self.dockwidget.combo_layers.setCurrentText(curlayer.name())

        self.layer = self.dockwidget.combo_layers.currentData()
        if self.layer:
            self.connInfo = QgsDataSourceUri(self.layer.dataProvider().dataSourceUri(expandAuthConfig=True))

        self.populateFilterFields()

    def populateFilterFields(self):
        self.clearFieldsLayout(self.fieldsLayout)

        if self.dockwidget.combo_layers.count() <= 0:
            return
        dockWidgetContents = QtWidgets.QWidget()
        sellayer = self.dockwidget.combo_layers.currentText()
        ava_fields = self.settings["Layers"][sellayer]["fields"]

        """
        # сортировка полей в 2 столбца. Порядок по вертикали
        """
        # cnt = len(ava_fields)
        # med_cnt = (len(ava_fields))/2
        # rmed_cnt = int(med_cnt + (0.5 if med_cnt > 0 else -0.5))

        # for index, num in enumerate(range(0, rmed_cnt)):
        #     field_name = list(ava_fields)[num]
        #     self.addWidget(index, field_name, ava_fields[field_name], 0, dockWidgetContents)
        # for index, num in enumerate(range(rmed_cnt, cnt)):
        #     field_name = list(ava_fields)[num]
        #     self.addWidget(index, field_name, ava_fields[field_name], 2, dockWidgetContents)

        """
        # сортировка полей в N столбцов. Порядок по горизонтали
        """
        # column_count = self.settings["Layers"][sellayer].get("columns_count", 2) * 2
        # row = 0
        # column = 0
        # for field_name in ava_fields:
        #     if column >= column_count - 1:
        #         column = 0
        #         row += 1
        #     self.addWidget(row, field_name, ava_fields[field_name], column, dockWidgetContents)
        #     column += 2

        """
        # сортировка полей в N столбцов. Порядок по вертикали
        """
        column_count = self.settings["Layers"][sellayer].get("columns_count", 1)
        cnt = len(ava_fields)

        for k in ava_fields.keys():
            if "col_span" in ava_fields[k].keys():
                colspan = ava_fields[k]["col_span"] 
                if colspan > 1:
                    cnt += colspan - 1

        column_size = cnt // column_count
        if column_size * column_count < cnt:
            column_size += 1
        row = 0
        column = 0
        for index, field_name in enumerate(ava_fields):
            if index > 0:
                row += 1
                if row >= column_size:
                    row = 0
                    column += 2
                while self.fieldsLayout.itemAtPosition(row, column):
                    row += 1
                    if row >= column_size:
                        row = 0
                        column += 2
            if not field_name.startswith("__"):
                try:
                    self.addWidget(row, field_name, ava_fields[field_name], column, dockWidgetContents)
                except Exception as e:
                    print('Field "{0}" error: {1}'.format(field_name, e))

    def addWidget(self, row_num, field_name, field, column_num, content):
        label = QtWidgets.QLabel(content)
        label.setObjectName("label_" + field_name) 
        label.setText("{1}  {0}:".format(field["label"], "|" if column_num > 0 else ""))
        self.fieldsLayout.addWidget(label, row_num, column_num, 1, 1)

        cell_size = field.get("col_span", 1)
        if cell_size > 1:
            cell_size += cell_size - 1

        isrange = field.get("isrange", False) == 'True'
        if not isrange:
            widget = self.constructWidget(field_name, field, content)
            if widget:
                widget.setObjectName(field_name) 
                self.fieldsLayout.addWidget(widget, row_num, column_num + 1, 1, cell_size)
        else:
            rangeLayout = QtWidgets.QHBoxLayout()
            rangeLayout.setObjectName("RHL_" + field_name)
            widget_from = self.constructWidget(field_name, field, content)
            widget_to = self.constructWidget(field_name, field, content)
            if widget_from and widget_to:
                widget_from.setObjectName(field_name + '_from') 
                rangeLayout.addWidget(widget_from)
                widget_to.setObjectName(field_name + '_to') 
                rangeLayout.addWidget(widget_to)
                self.fieldsLayout.addLayout(rangeLayout, row_num, column_num + 1, 1, cell_size)

    def constructWidget(self, field_name, field, content):
        widget = None
        source_type = field.get("source_type", None)
        if not source_type:
            return QgsFilterLineEdit(content)

        if source_type.lower() == "own":
            widget = self.createWidgetByOwnField(field_name, content)
        elif source_type.lower() == "layer":
            widget = self.createWidgetByLayer(field_name, field, content)
        elif source_type.lower() == "custom":
            widget = self.createWidgetCustom(field_name, field, content)
        elif source_type.lower() == "same":
            widget = self.createWidgetSame(field_name, field, content)
        elif source_type.lower() == "postgres":
            widget = self.createWidgetByPostgresTable(field_name, field, content)
        else:
            widget = QgsFilterLineEdit(content)

        if widget:
            minmax_size = field.get("minmax_size", None)
            if minmax_size:
                widget.setMinimumWidth(minmax_size[0])
                widget.setMaximumWidth(minmax_size[1])
        return widget

    def createWidgetSame(self, field_name, field, content):
        if "source_field" in field:
            source_field = field["source_field"]
            source_widget = (self.findWidgetByName(self.fieldsLayout, source_field))
            if source_widget.metaObject().className() == 'QComboBox':
                widget = QtWidgets.QComboBox(content)
                items = ((source_widget.itemData(i), source_widget.itemText(i))  for i in range(0, source_widget.count()))
                for item in items:
                    widget.addItem(item[1], QVariant(item[0]))
                widget.setCurrentIndex(-1)
                widget.setEditable(True)
                return widget
        print ("Same field not found. QgsFilterLineEdit was set.")
        return QgsFilterLineEdit(content)



    def findWidgetByName(self, layout, widget_name):
        for i in reversed(range(layout.count())): 
            if layout.itemAt(i).layout():
                widget = self.getFieldValue(layout.itemAt(i).layout(), widget_name)
                if widget: 
                    return widget
            elif layout.itemAt(i).widget():
                widget = layout.itemAt(i).widget()
                if widget.objectName() == widget_name:
                    return widget

    def createWidgetByPostgresTable(self, field_name, field, content):
        query_data = None
        field_key = None
        field_title = None
        try:
            query_data = field["query_data"]
            field_key = field["field_key"]
            field_title = field["field_title"]
        except Exception as e:
            print(e)
            return None

        comboBox = QtWidgets.QComboBox(content)
        comboBox.setEditable(True)

        if len(query_data) > 0:
            try:
                conn = psycopg2.connect(
                    "dbname='" + self.connInfo.database() + 
                    "' host='" + self.connInfo.host() + 
                    "' user='" + self.connInfo.username() + 
                    "' password='" + self.connInfo.password() + 
                    "' port='" + self.connInfo.port() + "'")
                cursor = conn.cursor(cursor_factory=RealDictCursor)

                cursor.execute(query_data)
                results = cursor.fetchall()
                for row in results:
                    comboBox.addItem(row[field_title], QVariant(row[field_key]))
            except Exception as e:
                print(e)
            finally:
                try:
                    cursor.close()
                except:
                    print("Cursor not found")
                try:
                    conn.close()
                except:
                    print("Connection not found")

        comboBox.setCurrentIndex(-1)
        return comboBox

    def createWidgetCustom(self, field_name, field, content):
        if field.get("field_type", "").lower() == "datetime":
            dateTimeEdit = QgsDateTimeEdit(content)
            dateTimeEdit.setAllowNull(True)
            dateTimeEdit.setDisplayFormat('dd.MM.yyyy')
            dateTimeEdit.clear()
            return dateTimeEdit
        elif field.get("field_type", "").lower() == "checkbox":
            checkBox = QtWidgets.QCheckBox(content)
            return checkBox
        elif field.get("field_type", "").lower() == "rangeint":
            lineEdit = QgsFilterLineEdit(content)
            lineEdit.setValidator(QIntValidator(-9999999999, 9999999999, None))
            return lineEdit
        elif field.get("field_type", "").lower() == 'rangefloat':
            lineEdit = QgsFilterLineEdit(content)
            lineEdit.setValidator(QDoubleValidator(-999999999999, 999999999999, 10, None))
            return lineEdit
        elif field.get("field_type", "").lower() == 'combobox':
            combobox = QtWidgets.QComboBox(content)
            if "combobox_values" in field:
                for val in field["combobox_values"]:
                    combobox.addItem(field["combobox_values"][val], QVariant(val))
            combobox.setCurrentIndex(-1)
            return combobox
        return QgsFilterLineEdit(content)

    def createWidgetByLayer(self, field_name, field, content):
        layer_name = None
        field_key = None
        field_title = None
        try:
            layer_name = field["layer_name"]
            field_key = field["field_key"]
        except Exception as e:
            print(e)
            return None

        comboBox = QtWidgets.QComboBox(content)
        comboBox.setEditable(True)

        if len(QgsProject.instance().mapLayersByName(layer_name)) < 1:
            raise NotImplementedError(f'Layer "{layer_name}" not found.')
        layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        field_title = field.get("field_title", layer.displayExpression())
        for feat in layer.getFeatures():
            comboBox.addItem(feat[field_title], QVariant(feat[field_key]))
        comboBox.setCurrentIndex(-1)
        return comboBox

    def createWidgetByOwnField(self, field_name, content):
        layer = self.dockwidget.combo_layers.currentData()
        idx_field = layer.fields().indexFromName(field_name)
        field_type = layer.editorWidgetSetup(idx_field).type()
        if not idx_field >= 0:
            print("Field {0} not found in the layer properties. QgsFilterLineEdit() was set instead settings value.".format(field_name))
            return QgsFilterLineEdit(content)

        if field_type == 'ValueMap':
            comboBox = QtWidgets.QComboBox(content)
            comboBox.setEditable(True)
            # comboBox.setSizeAdjustPolicy(2) # AdjustToMinimumContentsLengthWithIcon = 2
            valuemap = layer.editorWidgetSetup(idx_field).config()['map']
            for item in valuemap:
                first_key = list(item.keys())[0]
                itemvalue = item[first_key]
                if itemvalue == '{2839923C-8B7D-419E-B84B-CA2FE9B80EC7}':
                    itemvalue = None
                comboBox.addItem(first_key, QVariant(itemvalue))
            comboBox.setCurrentIndex(-1)
            return comboBox
        elif field_type == 'ValueRelation':
            comboBox = QtWidgets.QComboBox(content)
            comboBox.setEditable(True)
            # comboBox.setSizeAdjustPolicy(2) # AdjustToMinimumContentsLengthWithIcon = 2
            config = layer.editorWidgetSetup(idx_field).config()
            layer = QgsProject.instance().mapLayers()[config["Layer"]]
            for feat in layer.getFeatures():
                comboBox.addItem(feat[config["Value"]], QVariant(feat[config["Key"]]))
            comboBox.setCurrentIndex(-1)
            return comboBox
        elif field_type == 'RelationReference':
            comboBox = QtWidgets.QComboBox(content)
            comboBox.setEditable(True)
            # comboBox.setSizeAdjustPolicy(0) # AdjustToMinimumContentsLengthWithIcon = 2
            config = layer.editorWidgetSetup(idx_field).config()
            configRelation = config['Relation']
            relation = QgsProject.instance().relationManager().relation(configRelation)
            relLayer = relation.referencedLayer()
            relLayerKey = relation.fieldPairs()[field_name]
            for feat in relLayer.getFeatures():
                # ===================================================================== РАЗОБРАТЬСЯ В ДАННЫХ В СПРАВОЧНИКЕ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                try:
                    comboBox.addItem((feat[relLayer.displayExpression()]).strip(), QVariant(feat[relLayerKey]))
                except Exception as e:
                    pass
            comboBox.setCurrentIndex(-1)
            return comboBox
        elif field_type == 'CheckBox':
            checkBox = QtWidgets.QCheckBox(content)
            config = layer.editorWidgetSetup(idx_field).config()
            # checkedState = config["CheckedState"]
            # uncheckedState = config["UncheckedState"]
            return checkBox
        elif field_type == 'Range':
            config = layer.editorWidgetSetup(idx_field).config()
            # lineEdit = QtWidgets.QLineEdit(content)
            lineEdit = QgsFilterLineEdit(content)
            if type(config["Step"]) == int:
                lineEdit.setValidator(QIntValidator(config["Min"], config["Max"], None))
            else:
                lineEdit.setValidator(QDoubleValidator(config["Min"], config["Max"], config["Precision"], None))
            return lineEdit
        elif field_type == 'DateTime':
            dateTimeEdit = QgsDateTimeEdit(content)
            dateTimeEdit.setAllowNull(True)
            dateTimeEdit.setDisplayFormat('dd.MM.yyyy')
            dateTimeEdit.clear()
            return dateTimeEdit
        elif field_type == 'TextEdit':
            # lineEdit = QtWidgets.QLineEdit(content)
            lineEdit = QgsFilterLineEdit(content)
            return lineEdit
        return None

    def clearFieldsLayout(self, layout):
        # print("clear..")
        # print('count before: ', layout.objectName(), layout.count())
        for i in reversed(range(layout.count())): 
            if layout.itemAt(i).layout():
                self.clearFieldsLayout(layout.itemAt(i).layout())
                layout.itemAt(i).layout().setParent(None)
            elif layout.itemAt(i).widget():
                layout.itemAt(i).widget().setParent(None)  
        # print('count after: ', layout.count(), 'total: ',  self.fieldsLayout.count())

    def readQueryFromFile(self, query_path):
        query = ''
        with open(os.path.join(self.plugin_dir, query_path), "r") as read_file:
            query = read_file.read().replace('\n', ' ')
        return query

    def execSearch(self):
        self.dockwidget.tableResult.setRowCount(0)
        self.dockwidget.tableResult.sortItems(-1)
        self.dockwidget.tableResult.reset()

        sellayer = self.dockwidget.combo_layers.currentText()
        if self.layer:
            fields = self.settings["Layers"][sellayer]["fields"]
            self.column_key = self.settings["Layers"][sellayer]["column_key"]

            query = ""
            value_query = self.settings["Layers"][sellayer]["query"]
            if isinstance(value_query, list):
                query = "".join(value_query)
            elif isinstance(value_query, str):
                query = self.readQueryFromFile(value_query)

            attributes_values = self.generateQueryAttributesValues(fields)
            #print(attributes_values)

            if len(query) > 0:
                try:
                    conn = psycopg2.connect(
                        "dbname='" + self.connInfo.database() + "' host='" + self.connInfo.host() + 
                        "' user='" + self.connInfo.username() + "' password='" + self.connInfo.password() + 
                        "' port='" + self.connInfo.port() + "'")
                    cursor = conn.cursor(cursor_factory=RealDictCursor)

                    mogrified_query = cursor.mogrify(query, attributes_values)
                    # print(mogrified_query)
                    cursor.execute(mogrified_query)
                    results = cursor.fetchall()
                    # print(results)

                    cnt_rows = len(results)
                    self.iface.mainWindow().statusBar().showMessage(u'Всего найдено: ' + str(cnt_rows))
                    
                    table = self.dockwidget.tableResult
                    if cnt_rows > 0:
                        table.setEnabled(True)
                        headers = list(results[0].keys())
                        headers.insert(0, headers.pop(headers.index(self.column_key)))
                        cnt_cols = len(headers)

                        table.setRowCount(cnt_rows)
                        table.setColumnCount(cnt_cols)
                        table.setHorizontalHeaderLabels(headers)
                        table.setColumnHidden(0, True)
                        for rn in range(0, cnt_rows):
                            for cn in range(0, cnt_cols):
                                cell_result = results[rn][headers[cn]]
                                if cell_result is not None:
                                    item = QTableWidgetItem(str(cell_result))
                                    table.setItem(rn, cn, item)
                        table.resizeColumnsToContents()
                        table.resizeRowsToContents()
                    
                    else:
                        table.setEnabled(False)
                        table.setRowCount(1)
                        table.setColumnCount(1)
                        table.setHorizontalHeaderLabels([''])
                        table.setColumnHidden(0, False)
                        item = QTableWidgetItem(str('Нет данных для отображения'))
                        item.setTextAlignment(Qt.AlignCenter)
                        table.setItem(0, 0, item)

                except Exception as e:
                    print(e)
                finally:
                    cursor.close()
                    conn.close()

    def generateQueryAttributesValues(self, fields):
        values_dict = {}
        for field in fields:
            if not field == "_":
                isrange = fields[field].get("isrange", False) == 'True'
                if isrange:
                    value_from = self.getFieldValue(self.fieldsLayout, field + "_from")
                    values_dict[field + "_from"] = value_from
                    value_to = self.getFieldValue(self.fieldsLayout, field + "_to")
                    values_dict[field + "_to"] = value_to
                else:
                    value = self.getFieldValue(self.fieldsLayout, field)
                    values_dict[field] = value
        return values_dict

    def getFieldValue(self, layout, widget_name):
        for i in reversed(range(layout.count())): 
            if layout.itemAt(i).layout():
                widget = self.getFieldValue(layout.itemAt(i).layout(), widget_name)
                if widget: 
                    return widget
            elif layout.itemAt(i).widget():
                widget = layout.itemAt(i).widget()
                if widget.objectName() == widget_name:
                    if widget.metaObject().className() == 'QLineEdit':
                        # print('QLineEdit: ', widget_name)
                        value = widget.text().strip()
                        if not widget.validator() and len(value) > 0:
                            value = "%{}%".format(value)
                        return value if len(value) > 0 else None
                    if widget.metaObject().className() == 'QgsFilterLineEdit':
                        # print('QLineEdit: ', widget_name)
                        value = widget.value().strip()
                        if not widget.validator() and len(value) > 0:
                            value = "%{}%".format(value)
                        return value if len(value) > 0 else None
                    elif widget.metaObject().className() == 'QCheckBox':
                        # print('QCheckBox: ', widget_name)
                        value = widget.isChecked()
                        return True if value else None
                    elif widget.metaObject().className() == 'QComboBox':
                        # print('QComboBox: ', widget_name)
                        value = widget.currentData()
                        return value if value is not None and len(str(value)) > 0  else None
                    elif widget.metaObject().className() == 'QgsDateTimeEdit':
                        # print('QgsDateTimeEdit: ', widget_name)
                        # value_str = widget.text()
                        value_str = widget.date().toString('dd.MM.yyyy')
                        value = None
                        if (value_str != 'NULL' and len(value_str.strip()) > 0):
                            value = datetime.strptime(value_str, '%d.%m.%Y')
                        return value
        return None

    def execReset(self):
        self.clearWidgetsValues(self.fieldsLayout)

    def clearWidgetsValues(self, layout):
        for i in reversed(range(layout.count())): 
            if layout.itemAt(i).layout():
                self.clearWidgetsValues(layout.itemAt(i).layout())
            elif layout.itemAt(i).widget():
                widget = layout.itemAt(i).widget()
                if widget.metaObject().className() != 'QLabel':
                    try:
                        widget.setCurrentIndex(-1)
                    except:
                        try:
                            widget.setChecked(False)
                        except:
                            try:
                                widget.clear()
                            except Exception as e:
                                print(e)

    def execDoubleClickedTable(self, item):
        row = item.row()
        table = self.dockwidget.tableResult
        featuresById = self.layer.getFeatures("{0} = {1}".format(
                                                self.column_key,
                                                table.item(row, 0).text()))
        for feature in featuresById:
            self.iface.openFeatureForm(self.layer, feature, False, False)

    def centerToSelect(self):
        table = self.dockwidget.tableResult
        row = table.currentRow()
        featuresById = self.layer.getFeatures("{0} = {1}".format(
                                                self.column_key,
                                                table.item(row, 0).text()))
        self.layer.selectByIds([])
        for feature in featuresById:
            self.layer.select(feature.id())
            self.iface.mapCanvas().setCenter(feature.geometry().boundingBox().center())
            self.iface.mapCanvas().refresh()
            break
        del featuresById

    def zoomToSelect(self):
        table = self.dockwidget.tableResult
        row = table.currentRow()
        featuresById = self.layer.getFeatures("{0} = {1}".format(
                                                self.column_key,
                                                table.item(row, 0).text()))
        self.layer.selectByIds([])
        for feature in featuresById:
            self.layer.select(feature.id())

            box = None
            if self.layer.geometryType() == QgsWkbTypes.PointGeometry:
                box = feature.geometry().buffer(50, 1).boundingBox()
            else: # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!does not tested
                box = feature.geometry().buffer(50, 1).boundingBox()
            self.iface.mapCanvas().setExtent(box)
            self.iface.mapCanvas().refresh()
            break
        del featuresById

    def filterMapBySelect(self):
        table = self.dockwidget.tableResult
        selectedIds = []
        selectionModel = table.selectionModel()
        for modelIndex in selectionModel.selectedRows():
            selectedIds.append(table.item(modelIndex.row(), 0).text())
        if len(selectedIds) > 0:
            self.layer.setSubsetString('"{0}" in ({1})'.format(self.column_key, 
                                                               ', '.join(selectedIds)))
            ltw = self.iface.layerTreeView()
            ltw.refreshLayerSymbology(self.layer.id())

    def clearFilterMapBySelect(self):
        self.layer.setSubsetString('')
        ltw = self.iface.layerTreeView()
        ltw.refreshLayerSymbology(self.layer.id())

    def copySelected(self):
        table = self.dockwidget.tableResult
        selectionModel = table.selectionModel()
        colcount = table.columnCount()

        rowStrings = []
        headers = [table.horizontalHeaderItem(col).text() for col in range(colcount)]
        rowStrings.append('\t'.join(headers))

        for modelIndex in selectionModel.selectedRows():
            rowItemsStrings = []
            for columnIndex in range(colcount):
                item = table.item(modelIndex.row(), columnIndex)
                itemText = '""'
                if item:  
                    itemText = '"' + item.text().replace('"', '""') + '"'
                rowItemsStrings.append(itemText)
            rowStrings.append('\t'.join(rowItemsStrings))
        
        selectedResultString = '\n'.join(rowStrings)
        QApplication.clipboard().setText(selectedResultString)

    def setRowSelectedButtonsStatus(self):
        if self.dockwidget.tableResult.currentRow() >= 0:
            self.dockwidget.buttonCenter.setEnabled(True)
            self.dockwidget.buttonZoom.setEnabled(True)
        else:
            self.dockwidget.buttonCenter.setEnabled(False)
            self.dockwidget.buttonZoom.setEnabled(False)
            self.dockwidget.buttonFilterMap.setEnabled(False)

        if self.dockwidget.tableResult.selectionModel().hasSelection():
            self.dockwidget.buttonFilterMap.setEnabled(True)
            self.dockwidget.buttonCopy.setEnabled(True)
        else:
            self.dockwidget.buttonFilterMap.setEnabled(False)
            self.dockwidget.buttonCopy.setEnabled(False)

        if self.dockwidget.combo_layers.currentIndex() > -1:
            self.dockwidget.buttonClearFilterMap.setEnabled(True)
        else:
            self.dockwidget.buttonClearFilterMap.setEnabled(False)
