# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataSearcher
                                 A QGIS plugin
 Search data by preset queries in json
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-11
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Zlatanov Evgeniy
        email                : johnzet@yandex.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon, QIntValidator, QDoubleValidator
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.core import QgsProject, QgsVectorLayer, QgsRelation, QgsDataSourceUri
from qgsdatetimeedit import QgsDateTimeEdit
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .data_searcher_dockwidget import DataSearcherDockWidget
import os.path
import json
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import datetime


class DataSearcher:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
    
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DataSearcher_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Data Searcher')

        self.toolbar = self.iface.addToolBar(u'DataSearcher')
        self.toolbar.setObjectName(u'DataSearcher')

        #print "** INITIALIZING DataSearcher"

        self.pluginIsActive = False
        self.dockwidget = None

        self.settings = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DataSearcher', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/_Data_searcher/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Data searcher'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING DataSearcher"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False

        self.disconnectActions()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD DataSearcher"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Data Searcher'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING DataSearcher"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = DataSearcherDockWidget()
            self.connectActions()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            self.loadLayersData()
            self.populateComboLayers()

            self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

    def connectActions(self):
        self.dockwidget.buttonSearch.clicked.connect(self.execSearch)
        # self.dockwidget.combo_layers.currentIndexChanged.connect(self.comboLayersChanged) #move to populateComboLayers
        print("connect")

    def disconnectActions(self):
        self.dockwidget.buttonSearch.clicked.disconnect(self.execSearch)
        self.dockwidget.combo_layers.currentIndexChanged.disconnect(self.comboLayersChanged)
        print('disconnect')

    def loadLayersData(self):
        with open(os.path.join(self.plugin_dir, "settings.json"), "r") as read_file:
            self.settings = json.load(read_file)
            for layer in self.settings["Layers"].keys():
                self.dockwidget.combo_layers.addItem(layer)

    def comboLayersChanged(self):
        print("comboLayersChanged..")
        self.populateFilterFields()
        
    def populateFilterFields(self):
        self.clearFieldsLayout(self.dockwidget.fieldsLayout)

        dockWidgetContents = QtWidgets.QWidget()
        sellayer = self.dockwidget.combo_layers.currentText()
        ava_fields = self.settings["Layers"][sellayer]["fields"]
        
        """
        # сортировка полей в 2 столбца. Порядок по вертикали
        """
        # cnt = len(ava_fields)
        # med_cnt = (len(ava_fields))/2
        # rmed_cnt = int(med_cnt + (0.5 if med_cnt > 0 else -0.5))

        # for index, num in enumerate(range(0, rmed_cnt)):
        #     field_name = list(ava_fields)[num]
        #     self.addWidget(index, field_name, ava_fields[field_name], 0, dockWidgetContents)
        # for index, num in enumerate(range(rmed_cnt, cnt)):
        #     field_name = list(ava_fields)[num]
        #     self.addWidget(index, field_name, ava_fields[field_name], 2, dockWidgetContents)

        """
        # сортировка полей в N столбцов. Порядок по горизонтали
        """
        # column_count = self.settings["Layers"][sellayer].get("columns_count", 2) * 2
        # row = 0
        # column = 0
        # for field_name in ava_fields:
        #     if column >= column_count - 1:
        #         column = 0
        #         row += 1
        #     self.addWidget(row, field_name, ava_fields[field_name], column, dockWidgetContents)
        #     column += 2

        """
        # сортировка полей в N столбцов. Порядок по вертикали
        """
        column_count = self.settings["Layers"][sellayer].get("columns_count", 1)
        cnt = len(ava_fields)
        column_size = cnt // column_count
        print(0, column_size, cnt)
        if column_size * column_count < cnt:
            column_size += 1
            print(1, column_size)
        row = 0
        column = 0
        for field_name in ava_fields:
            if row >= column_size:
                row = 0
                column += 2
            if not field_name == "_":
                self.addWidget(row, field_name, ava_fields[field_name], column, dockWidgetContents)
            row += 1
                
    def addWidget(self, row_num, field_name, field, column_num, content):
        label = QtWidgets.QLabel(content)
        label.setObjectName("label_" + field_name) 
        label.setText("{1}  {0}:".format(field["label"], "|" if column_num > 0 else ""))
        self.dockwidget.fieldsLayout.addWidget(label, row_num, column_num, 1, 1)

        isrange = field.get("isrange", False) == 'True'
        if not isrange:
            widget = self.constructWidget(field_name, field, content)
            if widget:
                widget.setObjectName(field_name) 
                self.dockwidget.fieldsLayout.addWidget(widget, row_num, column_num + 1, 1, 1)
        else:
            rangeLayout = QtWidgets.QHBoxLayout()
            rangeLayout.setObjectName("RHL_" + field_name)
            widget_from = self.constructWidget(field_name, field, content)
            widget_to = self.constructWidget(field_name, field, content)
            if widget_from and widget_to:
                widget_from.setObjectName(field_name + '_from') 
                rangeLayout.addWidget(widget_from)
                widget_to.setObjectName(field_name + '_to') 
                rangeLayout.addWidget(widget_to)
                self.dockwidget.fieldsLayout.addLayout(rangeLayout, row_num, column_num + 1, 1, 1)
        
    
    def constructWidget(self, field_name, field, content):
        widget = None
        if field.get("source_type", "").lower() == "own":
            widget = self.createWidgetByOwnField(field_name, content)
        elif field.get("source_type", "").lower() == "layer":
            widget = self.createWidgetByLayer(field_name, field, content)
        elif field.get("source_type", "").lower() == "custom":
            widget = self.createWidgetCustom(field_name, field, content)
        else:
            widget = QtWidgets.QLineEdit(content)

        minmax_size = field.get("minmax_size", None)
        if minmax_size:
            widget.setMinimumWidth(minmax_size[0])
            widget.setMaximumWidth(minmax_size[1])
        return widget

    def createWidgetCustom(self, field_name, field, content):
        if field.get("field_type", "").lower() == "datetime":
            dateTimeEdit = QgsDateTimeEdit(content)
            dateTimeEdit.setAllowNull(True)
            dateTimeEdit.setDisplayFormat('dd.MM.yyyy')
            dateTimeEdit.clear()
            return dateTimeEdit
        elif field.get("field_type", "").lower() == "checkbox":
            checkBox = QtWidgets.QCheckBox(content)
            return checkBox
        elif field.get("field_type", "").lower() == "rangeint":
            lineEdit = QtWidgets.QLineEdit(content)
            lineEdit.setValidator(QIntValidator(-9999999999, 9999999999, None))
            return lineEdit
        elif field.get("field_type", "").lower() == 'rangefloat':
            lineEdit = QtWidgets.QLineEdit(content)
            lineEdit.setValidator(QDoubleValidator(-999999999999, 999999999999, 10, None))
            return lineEdit
        elif field.get("field_type", "").lower() == 'combobox':
            combobox = QtWidgets.QComboBox(content)
            if "combobox_values" in field:
                for val in field["combobox_values"]:
                    combobox.addItem(field["combobox_values"][val], QVariant(val))
            combobox.setCurrentIndex(-1)
            return combobox
        return QtWidgets.QLineEdit(content)


    def createWidgetByLayer(self, field_name, field, content):
        layer_name = None
        field_key = None
        field_title = None
        try:
            layer_name = field["layer_name"]
            field_key = field["field_key"]
        except Exception as e:
            print(e)
            return None

        comboBox = QtWidgets.QComboBox(content)
        comboBox.setEditable(True)

        layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        field_title = field.get("field_title", layer.displayExpression())
        for feat in layer.getFeatures():
            comboBox.addItem(feat[field_title], QVariant(feat[field_key]))
        comboBox.setCurrentIndex(-1)
        return comboBox

    def createWidgetByOwnField(self, field_name, content):
        layer = self.dockwidget.combo_layers.currentLayer()
        idx_field = layer.fields().indexFromName(field_name)
        field_type = layer.editorWidgetSetup(idx_field).type()

        if field_type == 'ValueMap':
            comboBox = QtWidgets.QComboBox(content)
            comboBox.setEditable(True)
            # comboBox.setSizeAdjustPolicy(2) # AdjustToMinimumContentsLengthWithIcon = 2
            valuemap = layer.editorWidgetSetup(idx_field).config()['map']
            for item in valuemap:
                first_key = list(item.keys())[0]
                comboBox.addItem(first_key, QVariant(item[first_key]))
            comboBox.setCurrentIndex(-1)
            return comboBox
        elif field_type == 'ValueRelation':
            comboBox = QtWidgets.QComboBox(content)
            comboBox.setEditable(True)
            # comboBox.setSizeAdjustPolicy(2) # AdjustToMinimumContentsLengthWithIcon = 2
            config = layer.editorWidgetSetup(idx_field).config()
            layer = QgsProject.instance().mapLayers()[config["Layer"]]
            for feat in layer.getFeatures():
                comboBox.addItem(feat[config["Value"]], QVariant(feat[config["Key"]]))
            comboBox.setCurrentIndex(-1)
            return comboBox
        elif field_type == 'RelationReference':
            comboBox = QtWidgets.QComboBox(content)
            comboBox.setEditable(True)
            # comboBox.setSizeAdjustPolicy(0) # AdjustToMinimumContentsLengthWithIcon = 2
            config = layer.editorWidgetSetup(idx_field).config()
            configRelation = config['Relation']
            relation = QgsProject.instance().relationManager().relation(configRelation)
            relLayer = relation.referencedLayer()
            relLayerKey = relation.fieldPairs()[field_name]
            for feat in relLayer.getFeatures():
                # ===================================================================== РАЗОБРАТЬСЯ В ДАННЫХ В СПРАВОЧНИКЕ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                try:
                    comboBox.addItem((feat[relLayer.displayExpression()]).strip(), QVariant(feat[relLayerKey]))
                except Exception as e:
                    pass
            comboBox.setCurrentIndex(-1)
            return comboBox
        elif field_type == 'CheckBox':
            checkBox = QtWidgets.QCheckBox(content)
            config = layer.editorWidgetSetup(idx_field).config()
            # checkedState = config["CheckedState"]
            # uncheckedState = config["UncheckedState"]
            return checkBox
        elif field_type == 'Range':
            config = layer.editorWidgetSetup(idx_field).config()
            lineEdit = QtWidgets.QLineEdit(content)
            if type(config["Step"]) == int:
                lineEdit.setValidator(QIntValidator(config["Min"], config["Max"], None))
            else:
                lineEdit.setValidator(QDoubleValidator(config["Min"], config["Max"], config["Precision"], None))
            return lineEdit
        elif field_type == 'DateTime':
            dateTimeEdit = QgsDateTimeEdit(content)
            dateTimeEdit.setAllowNull(True)
            dateTimeEdit.setDisplayFormat('dd.MM.yyyy')
            dateTimeEdit.clear()
            return dateTimeEdit
        elif field_type == 'TextEdit':
            lineEdit = QtWidgets.QLineEdit(content)
            return lineEdit
        return None

    def clearFieldsLayout(self, layout):
        # print("clear..")
        # print('count before: ', layout.objectName(), layout.count())
        for i in reversed(range(layout.count())): 
            if layout.itemAt(i).layout():
                self.clearFieldsLayout(layout.itemAt(i).layout())
                layout.itemAt(i).layout().setParent(None)
            elif layout.itemAt(i).widget():
                layout.itemAt(i).widget().setParent(None)  
        # print('count after: ', layout.count(), 'total: ',  self.dockwidget.fieldsLayout.count())

    def populateComboLayers(self):
        available_layers = self.settings["Layers"].keys()
        layer_list = []
        for layer in QgsProject.instance().mapLayers().values():
            if layer.name() not in available_layers:
                layer_list.append(layer)
        self.dockwidget.combo_layers.setExceptedLayerList(layer_list)

        curlayer = self.iface.activeLayer()
        if curlayer is not None:
            if curlayer.name() in available_layers:
                self.dockwidget.combo_layers.setCurrentText(curlayer.name())
        self.populateFilterFields()

        self.dockwidget.combo_layers.currentIndexChanged.connect(self.comboLayersChanged)
        # print('populated')

    def execSearch(self):
        self.dockwidget.tableResult.setRowCount(0)
        self.dockwidget.tableResult.sortItems(-1)

        layer = self.dockwidget.combo_layers.currentLayer()
        connInfo = QgsDataSourceUri(layer.dataProvider().dataSourceUri(expandAuthConfig=True))
        pwd = connInfo.password()
        username = connInfo.username()
        wkbtype = connInfo.wkbType()
        table = connInfo.table()
        schema = connInfo.schema()
        server_ip = connInfo.host()
        database = connInfo.database()
        port = connInfo.port()
        geom = connInfo.geometryColumn()

        #print(connInfo, pwd, username, wkbtype, table, schema, server_ip, database, port, geom)

        sellayer = self.dockwidget.combo_layers.currentText()
        fields = self.settings["Layers"][sellayer]["fields"]
        query = "".join(self.settings["Layers"][sellayer]["query"])

        attributes_values = self.generateQueryAttributesValues(fields)
        print(attributes_values)
        # return

        if len(query) > 0 and pwd and username:
            try:
                conn = psycopg2.connect(
                    "dbname='" + database + "' host='" + server_ip + 
                    "' user='" + username + "' password='" + pwd + "'")
                cursor = conn.cursor(cursor_factory=RealDictCursor)

                mogrified_query = cursor.mogrify(query, attributes_values)
                print(mogrified_query)
                cursor.execute(mogrified_query)
                results = cursor.fetchall()
                print(results)

                

                # cnt_row = len(results)
                # cnt_col = len(fields)

                # self.dockwidget.tableResult.setRowCount(cnt_row)
                # self.dockwidget.tableResult.setColumnCount(cnt_col)

            except Exception as e:
                print(e)
            finally:
                cursor.close()
                conn.close()

        # self.iface.messageBar().pushMessage(u"asdasd", u"sadasd", duration=2, level=2)

    def generateQueryAttributesValues(self, fields):
        values_dict = {}
        for field in fields:
            if not field == "_":
                isrange = fields[field].get("isrange", False) == 'True'
                if isrange:
                    value_from = self.findFieldWidgetByName(self.dockwidget.fieldsLayout, field + "_from")
                    values_dict[field + "_from"] = value_from
                    value_to = self.findFieldWidgetByName(self.dockwidget.fieldsLayout, field + "_to")
                    values_dict[field + "_to"] = value_to
                else:
                    value = self.findFieldWidgetByName(self.dockwidget.fieldsLayout, field)
                    values_dict[field] = value
        return values_dict

    def findFieldWidgetByName(self, layout, widget_name):
        for i in reversed(range(layout.count())): 
            if layout.itemAt(i).layout():
                widget = self.findFieldWidgetByName(layout.itemAt(i).layout(), widget_name)
                if widget: 
                    return widget
            elif layout.itemAt(i).widget():
                widget = layout.itemAt(i).widget()
                if widget.objectName() == widget_name:
                    if widget.metaObject().className() == 'QLineEdit':
                        print('QLineEdit: ', widget_name)
                        value = widget.text().strip().lower()
                        return value if len(value) > 0 else None
                    elif widget.metaObject().className() == 'QCheckBox':
                        print('QCheckBox: ', widget_name)
                        value = widget.isChecked()
                        return True if value else None
                    elif widget.metaObject().className() == 'QComboBox':
                        print('QComboBox: ', widget_name)
                        value = widget.currentData()
                        return value if value is not None and len(str(value)) > 0  else None
                    elif widget.metaObject().className() == 'QgsDateTimeEdit':
                        print('QgsDateTimeEdit: ', widget_name)
                        value_str = widget.text()
                        value = None
                        if value_str != 'NULL':
                            value = datetime.strptime(value_str, '%d.%m.%Y')
                        return value
        return None